FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api ./api

# fichiers DVC
COPY dvc.yaml dvc.lock .dvc/config ./

CMD dvc pull && \
    uvicorn api.main:app --host 0.0.0.0 --port 8000
