FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY .dvc .dvc
COPY dvc.yaml .
COPY dvc.lock .
COPY .dvc/config .dvc/config

COPY api ./api

RUN git init

CMD ["bash", "-c", "dvc pull && uvicorn main:app --host 0.0.0.0 --port 8000"]


